version: "3.7"

services:
  arbot:
    image: mkv28/arbot-mkv
    network_mode: host
    restart: always
    container_name: arbot
    volumes:
      # Direktori unduhan aria2, default
      - /root/downloads:/root/downloads
      # Mount direktori custom untuk memudahkan menghapus file setelah mengirim telgram, jika tidak diatur, container tidak akan menemukan direktori tersebut
      - /Khusus:/Khusus
    environment:
      TZ: Asia/Jakarta
      API_ID: 11111
      API_HASH: 11111
      BOT_TOKEN: 11111:11111
      JSON_RPC_URL: http://11111:6800/jsonrpc
      JSON_RPC_TOKEN: 11111
      SEND_ID: 11111
      #      PROXY_IP:   # ip proxy opsional
      #      PROXY_PORT:  # port proxy opsional
      UP_TELEGRAM: 'False' # Apakah akan mengunggah Telegram
